export interface Question {
  id: number;
  q: string;
  opts: [string, string, string, string];
  ans: number; // 0-indexed
}

export interface AssessmentTrack {
  slug: string;
  label: string;
  duration: number; // minutes
  questions: Question[];
}

const aptitude: Question[] = [
  { id:1,  q:"A train travels 360 km in 4 hours. What is its speed in m/s?", opts:["25 m/s","90 m/s","72 m/s","30 m/s"], ans:0 },
  { id:2,  q:"If 12 men can do a job in 18 days, how many days will 9 men take?", opts:["24 days","21 days","27 days","18 days"], ans:0 },
  { id:3,  q:"The ratio of A's salary to B's salary is 3:5. If B earns ₹25,000, what does A earn?", opts:["₹15,000","₹12,000","₹18,000","₹20,000"], ans:0 },
  { id:4,  q:"A shopkeeper sells an item at ₹840 making a 20% profit. What is the cost price?", opts:["₹700","₹720","₹680","₹750"], ans:0 },
  { id:5,  q:"Find the missing number: 2, 6, 12, 20, 30, ?", opts:["42","40","44","36"], ans:0 },
  { id:6,  q:"If APPLE is coded as 54, what is the code for MANGO?", opts:["55","52","60","57"], ans:0 },
  { id:7,  q:"Simple interest on ₹5,000 at 8% p.a. for 3 years is:", opts:["₹1,200","₹1,000","₹1,500","₹800"], ans:0 },
  { id:8,  q:"A pipe fills a tank in 6 hours and another empties it in 9 hours. Both open together, tank fills in:", opts:["18 hours","12 hours","15 hours","24 hours"], ans:0 },
  { id:9,  q:"What is 15% of 240?", opts:["36","32","40","24"], ans:0 },
  { id:10, q:"If x + y = 10 and xy = 21, what is x² + y²?", opts:["58","42","100","79"], ans:0 },
  { id:11, q:"A car depreciates by 10% each year. Original value ₹1,00,000. Value after 2 years?", opts:["₹81,000","₹80,000","₹82,000","₹90,000"], ans:0 },
  { id:12, q:"The average of 5 numbers is 40. If one number is removed the average becomes 35. The removed number is:", opts:["60","55","65","45"], ans:0 },
  { id:13, q:"Which comes next in the sequence: ACE, BDF, CEG, ?", opts:["DFH","DEG","CFH","EGI"], ans:0 },
  { id:14, q:"Two numbers are in ratio 4:7. Their LCM is 168. Their HCF is:", opts:["6","4","8","12"], ans:0 },
  { id:15, q:"If 40% of a number is 120, what is 75% of that number?", opts:["225","210","200","250"], ans:0 },
  { id:16, q:"A walks at 5 km/h and B at 7 km/h. They start from the same point in opposite directions. After 3 hours, distance between them:", opts:["36 km","24 km","45 km","30 km"], ans:0 },
  { id:17, q:"Compound interest on ₹8,000 at 10% p.a. for 2 years is:", opts:["₹1,680","₹1,600","₹1,700","₹1,800"], ans:0 },
  { id:18, q:"A rectangle's length is doubled and width halved. Area change:", opts:["No change","Doubled","Halved","Quadrupled"], ans:0 },
  { id:19, q:"REARRANGE 'LISTEN' — which word does it form?", opts:["SILENT","TINSEL","ENLIST","SLITEN"], ans:0 },
  { id:20, q:"Which is the odd one out: 3, 5, 7, 9, 11?", opts:["9","5","7","11"], ans:0 },
];

const digitalMarketing: Question[] = [
  { id:1,  q:"What does SEO stand for?", opts:["Search Engine Optimisation","Social Engagement Optimisation","Search Engagement Output","Site Engine Operation"], ans:0 },
  { id:2,  q:"Which metric measures the % of visitors who leave after one page?", opts:["Bounce Rate","CTR","CPC","CPM"], ans:0 },
  { id:3,  q:"What is a 'long-tail keyword'?", opts:["A highly specific multi-word phrase","A keyword with high search volume","A keyword under 3 characters","A paid keyword"], ans:0 },
  { id:4,  q:"Google Ads operates primarily on which pricing model?", opts:["Pay-Per-Click","Pay-Per-Impression","Pay-Per-View","Pay-Per-Lead"], ans:0 },
  { id:5,  q:"What does a higher Quality Score in Google Ads indicate?", opts:["Relevant ad, keyword, and landing page","More ad spend","Longer ad text","More impressions"], ans:0 },
  { id:6,  q:"Which social platform is best suited for B2B marketing?", opts:["LinkedIn","Instagram","Snapchat","Pinterest"], ans:0 },
  { id:7,  q:"What is the primary purpose of a UTM parameter?", opts:["Track campaign traffic in analytics","Improve page speed","Increase domain authority","Compress images"], ans:0 },
  { id:8,  q:"What does CTR stand for?", opts:["Click-Through Rate","Cost To Reach","Customer Traffic Report","Content Targeting Ratio"], ans:0 },
  { id:9,  q:"Which type of SEO focuses on link building?", opts:["Off-page SEO","On-page SEO","Technical SEO","Local SEO"], ans:0 },
  { id:10, q:"What is 'retargeting' in digital advertising?", opts:["Serving ads to users who previously visited your site","Targeting new audiences","Sending email to new subscribers","Creating lookalike audiences"], ans:0 },
  { id:11, q:"Which Google Analytics metric shows the % of sessions with a conversion?", opts:["Conversion Rate","Bounce Rate","Sessions","Pageviews"], ans:0 },
  { id:12, q:"What does ROI stand for in marketing?", opts:["Return on Investment","Rate of Interest","Reach of Influence","Revenue on Impressions"], ans:0 },
  { id:13, q:"Which email marketing metric tells you how many opened your email?", opts:["Open Rate","CTR","Unsubscribe Rate","Delivery Rate"], ans:0 },
  { id:14, q:"A/B testing in digital marketing compares:", opts:["Two versions of content to see which performs better","Two different target audiences","Two ad budgets","Two social platforms"], ans:0 },
  { id:15, q:"What is Domain Authority (DA)?", opts:["A metric predicting a site's ranking ability","The age of a domain","The number of indexed pages","Daily active users"], ans:0 },
  { id:16, q:"Which strategy involves creating content to attract organic traffic?", opts:["Content Marketing","SEM","Display Advertising","Affiliate Marketing"], ans:0 },
  { id:17, q:"Instagram's algorithm prioritises content based on:", opts:["Engagement (likes, comments, saves)","Follower count only","Posting frequency only","Ad spend"], ans:0 },
  { id:18, q:"What is a 'funnel' in digital marketing?", opts:["Stages a buyer goes through from awareness to purchase","A tool for tracking emails","An SEO technique","A type of ad format"], ans:0 },
  { id:19, q:"Which tool is commonly used for keyword research?", opts:["Google Keyword Planner","Google Analytics","Google Search Console","Google Tag Manager"], ans:0 },
  { id:20, q:"What is 'organic reach' on social media?", opts:["Number of people who see content without paid promotion","Total followers","Paid ad impressions","Influencer shares"], ans:0 },
];

const dataScience: Question[] = [
  { id:1,  q:"Which Python library is primarily used for data manipulation?", opts:["Pandas","NumPy","Matplotlib","Scikit-learn"], ans:0 },
  { id:2,  q:"What does 'overfitting' mean in ML?", opts:["Model fits training data too well but fails on new data","Model fails on training data","Model has too few parameters","Model trains too quickly"], ans:0 },
  { id:3,  q:"Which algorithm is used for classification and regression?", opts:["Random Forest","K-Means","DBSCAN","PCA"], ans:0 },
  { id:4,  q:"What does 'p-value' indicate in hypothesis testing?", opts:["Probability of observing results given null hypothesis is true","The accuracy of a model","Size of the dataset","Mean of the distribution"], ans:0 },
  { id:5,  q:"Which technique reduces dimensionality while retaining variance?", opts:["PCA","K-Means","Naive Bayes","Linear Regression"], ans:0 },
  { id:6,  q:"What is 'cross-validation' used for?", opts:["Evaluate model performance on unseen data","Clean missing values","Encode categorical data","Scale features"], ans:0 },
  { id:7,  q:"Which loss function is typically used for binary classification?", opts:["Binary Cross-Entropy","MSE","MAE","Huber Loss"], ans:0 },
  { id:8,  q:"What type of learning is K-Means clustering?", opts:["Unsupervised","Supervised","Reinforcement","Semi-supervised"], ans:0 },
  { id:9,  q:"What does a confusion matrix measure?", opts:["Classification model performance across classes","Regression error","Data correlation","Feature importance"], ans:0 },
  { id:10, q:"Which Python library is used for deep learning by Google?", opts:["TensorFlow","Scikit-learn","Statsmodels","Seaborn"], ans:0 },
  { id:11, q:"What is the median of [3, 7, 9, 1, 5]?", opts:["5","7","3","9"], ans:0 },
  { id:12, q:"Which method handles missing values by removing rows?", opts:["Listwise deletion","Imputation","Interpolation","Encoding"], ans:0 },
  { id:13, q:"Pearson correlation ranges between:", opts:["-1 and 1","0 and 1","0 and 100","-100 and 100"], ans:0 },
  { id:14, q:"What is 'feature engineering'?", opts:["Creating new features from raw data to improve models","Removing unnecessary columns","Splitting data into train/test","Normalising data"], ans:0 },
  { id:15, q:"The bias-variance tradeoff refers to:", opts:["Balance between underfitting and overfitting","Speed vs accuracy","Memory vs speed","Model size vs accuracy"], ans:0 },
  { id:16, q:"Which metric is best for imbalanced classification datasets?", opts:["F1-Score","Accuracy","MSE","R²"], ans:0 },
  { id:17, q:"What does RMSE measure?", opts:["Root Mean Squared Error of predictions","Recall and MSE","Range of model scores","Regularisation parameter"], ans:0 },
  { id:18, q:"Which chart best shows distribution of continuous data?", opts:["Histogram","Pie chart","Bar chart","Scatter plot"], ans:0 },
  { id:19, q:"What is the purpose of normalisation in ML?", opts:["Scale features to a common range","Remove outliers","Encode text","Split datasets"], ans:0 },
  { id:20, q:"Gradient descent optimises by:", opts:["Iteratively moving towards minimum loss","Randomly sampling weights","Removing features","Adding layers"], ans:0 },
];

const dataAnalyst: Question[] = [
  { id:1,  q:"Which SQL clause filters grouped data?", opts:["HAVING","WHERE","GROUP BY","ORDER BY"], ans:0 },
  { id:2,  q:"What does VLOOKUP do in Excel?", opts:["Looks up a value in the first column and returns from another column","Filters rows","Sorts data","Creates pivot tables"], ans:0 },
  { id:3,  q:"Which chart type is best for showing trends over time?", opts:["Line chart","Pie chart","Bar chart","Scatter plot"], ans:0 },
  { id:4,  q:"What is a primary key in a database?", opts:["Unique identifier for each row","A foreign table reference","An indexed column","A computed column"], ans:0 },
  { id:5,  q:"What does the SQL INNER JOIN return?", opts:["Rows matching in both tables","All rows from left table","All rows from right table","All rows from both tables"], ans:0 },
  { id:6,  q:"In Power BI, what is a 'measure'?", opts:["A calculated aggregation (DAX formula)","A table column","A report page","A data source"], ans:0 },
  { id:7,  q:"Which Excel function counts non-empty cells?", opts:["COUNTA","COUNT","SUM","COUNTIF"], ans:0 },
  { id:8,  q:"What is an outlier in data analysis?", opts:["A data point far from other observations","A missing value","A duplicate row","A categorical variable"], ans:0 },
  { id:9,  q:"What does KPI stand for?", opts:["Key Performance Indicator","Key Process Index","Known Performance Item","Key Product Insight"], ans:0 },
  { id:10, q:"Which SQL function returns the number of rows?", opts:["COUNT","SUM","AVG","MAX"], ans:0 },
  { id:11, q:"A pivot table in Excel is used to:", opts:["Summarise and reorganise data dynamically","Write macros","Create charts","Filter columns"], ans:0 },
  { id:12, q:"What is 'data normalisation' in databases?", opts:["Organising data to reduce redundancy","Scaling numeric columns","Encoding categorical data","Removing outliers"], ans:0 },
  { id:13, q:"Which is NOT a measure of central tendency?", opts:["Variance","Mean","Median","Mode"], ans:0 },
  { id:14, q:"What does ETL stand for?", opts:["Extract, Transform, Load","Edit, Test, Launch","Evaluate, Train, Learn","Export, Transfer, Log"], ans:0 },
  { id:15, q:"Which SQL statement modifies existing data?", opts:["UPDATE","INSERT","DELETE","SELECT"], ans:0 },
  { id:16, q:"What is a 'heat map' used for?", opts:["Showing data density/intensity across dimensions","Tracking temperatures","Displaying network graphs","Showing time series"], ans:0 },
  { id:17, q:"Tableau is primarily a tool for:", opts:["Data visualisation","Database management","Data cleaning","ML model training"], ans:0 },
  { id:18, q:"In statistics, standard deviation measures:", opts:["Spread of data around the mean","Most frequent value","Middle value","Sum of values"], ans:0 },
  { id:19, q:"Which join returns all rows from the left table plus matching rows from the right?", opts:["LEFT JOIN","INNER JOIN","FULL OUTER JOIN","RIGHT JOIN"], ans:0 },
  { id:20, q:"What is the purpose of the GROUP BY clause in SQL?", opts:["Group rows with the same values for aggregation","Sort results","Filter individual rows","Limit result count"], ans:0 },
];

const fullStack: Question[] = [
  { id:1,  q:"What does REST stand for?", opts:["Representational State Transfer","Remote Execution State Transfer","Realtime Event State Transport","Resource Entity State Transfer"], ans:0 },
  { id:2,  q:"In React, what is the Virtual DOM?", opts:["A lightweight in-memory representation of the real DOM","A browser API","A CSS preprocessor","A server-side rendering engine"], ans:0 },
  { id:3,  q:"Which HTTP method is idempotent and retrieves data?", opts:["GET","POST","PATCH","DELETE"], ans:0 },
  { id:4,  q:"What does CORS stand for?", opts:["Cross-Origin Resource Sharing","Client Origin Request System","Cross-Object Rendering Spec","Content Origin Resolution Standard"], ans:0 },
  { id:5,  q:"Which database is schema-less (NoSQL)?", opts:["MongoDB","PostgreSQL","MySQL","SQLite"], ans:0 },
  { id:6,  q:"What is the purpose of JWT (JSON Web Token)?", opts:["Stateless authentication/authorisation","Database connection","Server-to-server messaging","Caching"], ans:0 },
  { id:7,  q:"In Node.js, what is the event loop?", opts:["A mechanism that handles async callbacks","A CSS animation loop","A recursive function","A database query loop"], ans:0 },
  { id:8,  q:"What does CSS Flexbox's 'justify-content: space-between' do?", opts:["Distributes items evenly with space between","Centers items","Stretches items","Aligns items to start"], ans:0 },
  { id:9,  q:"Which React hook manages side effects?", opts:["useEffect","useState","useContext","useRef"], ans:0 },
  { id:10, q:"What is the purpose of a .env file?", opts:["Store environment variables securely","Cache static assets","Define CSS variables","Configure build scripts"], ans:0 },
  { id:11, q:"Which status code indicates 'Not Found'?", opts:["404","200","500","301"], ans:0 },
  { id:12, q:"What is middleware in Express.js?", opts:["Functions that run between request and response","Static file server","Template engine","Session store"], ans:0 },
  { id:13, q:"What is the purpose of npm/package.json?", opts:["Manage project dependencies and scripts","Compile TypeScript","Run tests","Generate API docs"], ans:0 },
  { id:14, q:"Which HTML tag is used for a semantic page section?", opts:["<section>","<div>","<span>","<article>"], ans:0 },
  { id:15, q:"What is SQL injection?", opts:["Inserting malicious SQL into a query via user input","A SQL optimisation technique","A type of database index","A stored procedure"], ans:0 },
  { id:16, q:"What does WebSocket provide over HTTP?", opts:["Persistent full-duplex communication","Faster file uploads","Better caching","Stateless requests"], ans:0 },
  { id:17, q:"Which is the correct way to center a div using CSS Grid?", opts:["place-items: center","float: center","margin: center","align: middle"], ans:0 },
  { id:18, q:"What is the difference between '==' and '===' in JavaScript?", opts:["=== checks type and value; == only checks value","Both are identical","== is faster","=== is for objects only"], ans:0 },
  { id:19, q:"What does 'async/await' solve in JavaScript?", opts:["Makes asynchronous code readable like synchronous code","Speeds up I/O","Prevents memory leaks","Handles CSS transitions"], ans:0 },
  { id:20, q:"In Next.js, what is a Server Component?", opts:["A component rendered on the server with no client JS bundle","A component stored on CDN","A server-only CSS module","A static HTML page"], ans:0 },
];

const pythonDeveloper: Question[] = [
  { id:1,  q:"What is the output of: print(type([]))?", opts:["<class 'list'>","<class 'tuple'>","<type 'list'>","list"], ans:0 },
  { id:2,  q:"Which keyword defines a function in Python?", opts:["def","func","function","define"], ans:0 },
  { id:3,  q:"What is the difference between a list and a tuple?", opts:["Tuples are immutable; lists are mutable","Tuples are faster but otherwise identical","Lists allow duplicates; tuples do not","Tuples support indexing; lists do not"], ans:0 },
  { id:4,  q:"What does the 'self' parameter in a Python class method refer to?", opts:["The current instance of the class","The class itself","The parent class","A global variable"], ans:0 },
  { id:5,  q:"What is a Python decorator?", opts:["A function that wraps another function to add behaviour","A CSS utility","A type annotation","A class method"], ans:0 },
  { id:6,  q:"Which built-in function returns the length of an object?", opts:["len()","size()","count()","length()"], ans:0 },
  { id:7,  q:"What does 'pip' stand for?", opts:["Pip Installs Packages","Python Index Protocol","Package Import Program","Python Interface Proxy"], ans:0 },
  { id:8,  q:"What is a lambda function in Python?", opts:["An anonymous one-line function","A function with multiple return values","A recursive function","A coroutine"], ans:0 },
  { id:9,  q:"Which Python data structure uses key-value pairs?", opts:["Dictionary","List","Set","Tuple"], ans:0 },
  { id:10, q:"What does 'with open(file) as f:' provide?", opts:["Automatic file closing via context manager","File locking","Binary file reading","Async file access"], ans:0 },
  { id:11, q:"What is list comprehension?", opts:["Concise syntax to create lists from iterables","A way to sort lists","A method to merge lists","A way to deep copy lists"], ans:0 },
  { id:12, q:"What does __init__ do in a Python class?", opts:["Initialises a new instance","Deletes an instance","Copies an instance","Imports the class"], ans:0 },
  { id:13, q:"Which module provides regular expressions in Python?", opts:["re","regex","string","pattern"], ans:0 },
  { id:14, q:"What is the output of: bool(0)?", opts:["False","True","0","None"], ans:0 },
  { id:15, q:"What is the purpose of *args in a function definition?", opts:["Accept variable number of positional arguments","Accept keyword arguments","Mark optional arguments","Return multiple values"], ans:0 },
  { id:16, q:"Which Python web framework is minimal and lightweight?", opts:["Flask","Django","Pyramid","Tornado"], ans:0 },
  { id:17, q:"What is a generator in Python?", opts:["A function that yields values lazily","A class that creates objects","A module for random numbers","A list sorted lazily"], ans:0 },
  { id:18, q:"What does 'try/except' handle?", opts:["Runtime exceptions","Syntax errors","Import errors","Indentation errors"], ans:0 },
  { id:19, q:"What is the GIL in Python?", opts:["Global Interpreter Lock — limits true multi-threading","A memory allocator","A type of variable scope","A garbage collection method"], ans:0 },
  { id:20, q:"What does enumerate() do?", opts:["Returns index and value pairs from an iterable","Converts a list to a dictionary","Sorts an iterable","Counts unique elements"], ans:0 },
];

const medicalCoding: Question[] = [
  { id:1,  q:"What coding system is used for diagnoses in medical billing?", opts:["ICD-10-CM","CPT","HCPCS","DRG"], ans:0 },
  { id:2,  q:"CPT codes are maintained by:", opts:["American Medical Association (AMA)","WHO","CMS","AHIMA"], ans:0 },
  { id:3,  q:"What does HCPCS stand for?", opts:["Healthcare Common Procedure Coding System","Health Care Patient Classification System","Hospital Coding Procedure Standard","Healthcare Claims Processing System"], ans:0 },
  { id:4,  q:"What is the ICD-10-CM code for Type 2 Diabetes Mellitus without complications?", opts:["E11.9","E10.9","E13.9","E14.9"], ans:0 },
  { id:5,  q:"What is a 'principal diagnosis'?", opts:["The condition chiefly responsible for the hospital admission","The first listed code","The most expensive condition","A secondary diagnosis"], ans:0 },
  { id:6,  q:"Which modifier indicates a procedure was performed bilaterally?", opts:["-50","-51","-52","-59"], ans:0 },
  { id:7,  q:"What does 'CC' stand for in medical coding?", opts:["Complication or Comorbidity","Certified Coder","Current Condition","Clinical Category"], ans:0 },
  { id:8,  q:"What is an EOB (Explanation of Benefits)?", opts:["A statement from insurer explaining claim adjudication","A patient consent form","An insurance policy document","A billing invoice"], ans:0 },
  { id:9,  q:"Which code set is used for outpatient procedures?", opts:["CPT","ICD-10-PCS","DRG","NDC"], ans:0 },
  { id:10, q:"What is upcoding?", opts:["Billing for a higher-level service than provided","Updating old codes","Adding additional diagnoses","Coding for bilateral procedures"], ans:0 },
  { id:11, q:"What does 'NEC' mean in ICD-10 coding?", opts:["Not Elsewhere Classified","Not Enough Criteria","Non-Emergency Condition","New Entry Code"], ans:0 },
  { id:12, q:"Which section of the CPT manual contains E/M codes?", opts:["99201-99499","10000-19999","70000-79999","80000-89999"], ans:0 },
  { id:13, q:"What is a 'clean claim'?", opts:["A claim submitted with no errors that is processable","A claim with no diagnoses","A claim under ₹1,000","A claim for preventive care"], ans:0 },
  { id:14, q:"What does ICD stand for?", opts:["International Classification of Diseases","International Coding Directory","Integrated Clinical Database","Internal Clinical Diagnostics"], ans:0 },
  { id:15, q:"HIPAA governs:", opts:["Patient privacy and data protection","Medical coding standards","Hospital accreditation","Drug pricing"], ans:0 },
  { id:16, q:"What is a 'bundled code' in CPT?", opts:["A code that includes multiple related services","A code for bundled payments","A deprecated code","A code requiring prior authorisation"], ans:0 },
  { id:17, q:"Which modifier indicates a service was reduced or eliminated?", opts:["-52","-50","-51","-59"], ans:0 },
  { id:18, q:"What does 'POA' indicate on a claim?", opts:["Present on Admission","Part of Agreement","Prior Outstanding Amount","Point of Access"], ans:0 },
  { id:19, q:"A Z code in ICD-10 is used for:", opts:["Factors influencing health status (not illness/injury)","Procedures","Drugs","Laboratory values"], ans:0 },
  { id:20, q:"What is the purpose of a charge master (chargemaster)?", opts:["A list of all billable services and their standard charges","A patient record database","A coding reference book","An insurance contract"], ans:0 },
];

const aiDs: Question[] = [
  { id:1,  q:"What is a neural network?", opts:["A computational model inspired by the brain with layers of nodes","A network of AI servers","A type of database","A programming paradigm"], ans:0 },
  { id:2,  q:"What does 'deep learning' refer to?", opts:["Neural networks with many hidden layers","Machine learning on big data","Any supervised learning","Fast model training"], ans:0 },
  { id:3,  q:"What is 'transfer learning'?", opts:["Reusing a pre-trained model on a new task","Moving data between servers","Training on multiple GPUs","Converting models between frameworks"], ans:0 },
  { id:4,  q:"What is the activation function in a neural network?", opts:["A function introducing non-linearity to node outputs","A weight initialisation method","A loss calculation function","A gradient update rule"], ans:0 },
  { id:5,  q:"What does NLP stand for?", opts:["Natural Language Processing","Neural Learning Protocol","Network Layer Processing","Non-Linear Programming"], ans:0 },
  { id:6,  q:"What is a Convolutional Neural Network (CNN) primarily used for?", opts:["Image recognition and processing","Time series forecasting","Text generation","Reinforcement learning"], ans:0 },
  { id:7,  q:"What is 'backpropagation'?", opts:["Algorithm that computes gradients and updates weights","Forward pass of a network","Data preprocessing step","A type of regularisation"], ans:0 },
  { id:8,  q:"What is a GAN (Generative Adversarial Network)?", opts:["Two networks (generator + discriminator) competing to generate realistic data","A graph attention network","A genetic algorithm variant","A general adversarial node"], ans:0 },
  { id:9,  q:"What is 'reinforcement learning'?", opts:["An agent learns by receiving rewards/penalties for actions","Supervised learning with labels","Clustering without labels","Regression analysis"], ans:0 },
  { id:10, q:"Which framework is developed by Facebook/Meta for deep learning?", opts:["PyTorch","TensorFlow","Keras","MXNet"], ans:0 },
  { id:11, q:"What is an 'embedding' in NLP?", opts:["A dense vector representation of words/tokens","A compression algorithm","A model evaluation metric","A data augmentation method"], ans:0 },
  { id:12, q:"What does 'dropout' prevent in neural networks?", opts:["Overfitting by randomly deactivating neurons during training","Underfitting","Vanishing gradients","Exploding gradients"], ans:0 },
  { id:13, q:"What is the 'attention mechanism' in transformers?", opts:["A way to weigh the importance of different input tokens","A data cleaning step","A type of loss function","A GPU acceleration technique"], ans:0 },
  { id:14, q:"What is an RNN (Recurrent Neural Network) designed for?", opts:["Sequential/time-series data","Static images","Tabular data","Clustering"], ans:0 },
  { id:15, q:"What is 'batch normalisation'?", opts:["Normalising layer inputs to stabilise and speed up training","Normalising the dataset","Batching training data","Regularising weights"], ans:0 },
  { id:16, q:"What is the purpose of a confusion matrix in classification?", opts:["Shows TP, FP, TN, FN counts across classes","Shows model weights","Shows training loss","Shows feature importance"], ans:0 },
  { id:17, q:"What is 'hyperparameter tuning'?", opts:["Optimising settings like learning rate and batch size","Training additional layers","Fine-tuning model weights","Cleaning the dataset"], ans:0 },
  { id:18, q:"What is 'data augmentation' used for?", opts:["Artificially expanding training data to reduce overfitting","Removing duplicate data","Encoding categorical data","Scaling features"], ans:0 },
  { id:19, q:"What distinguishes AI from ML?", opts:["AI is the broader field; ML is a subset using statistical learning","ML is broader; AI is only robotics","They are identical terms","AI uses only rule-based systems"], ans:0 },
  { id:20, q:"What is 'semantic segmentation' in computer vision?", opts:["Classifying each pixel in an image with a label","Detecting bounding boxes","Recognising faces","Generating image captions"], ans:0 },
];

const frontendDeveloper: Question[] = [
  { id:1,  q:"What does HTML stand for?", opts:["HyperText Markup Language","Hyperlink and Text Markup Language","High-level Text Machine Language","HyperText Management Language"], ans:0 },
  { id:2,  q:"Which CSS property controls the stacking order of elements?", opts:["z-index","position","display","overflow"], ans:0 },
  { id:3,  q:"What is the CSS Box Model?", opts:["content + padding + border + margin","Only content and border","Content + padding only","Margin + border only"], ans:0 },
  { id:4,  q:"Which HTML element provides semantic navigation links?", opts:["<nav>","<div>","<header>","<ul>"], ans:0 },
  { id:5,  q:"In JavaScript, what does 'closure' mean?", opts:["A function retaining access to its outer scope after execution","A way to close browser windows","A CSS animation state","A method to end a loop"], ans:0 },
  { id:6,  q:"What is the purpose of React's useState hook?", opts:["Manage component-level state","Fetch data","Handle routing","Apply CSS classes"], ans:0 },
  { id:7,  q:"What does 'responsive design' mean?", opts:["A layout that adapts to different screen sizes","A fast-loading website","An animated UI","A type of CMS"], ans:0 },
  { id:8,  q:"Which CSS unit is relative to the root font size?", opts:["rem","em","px","vh"], ans:0 },
  { id:9,  q:"What is event bubbling in JavaScript?", opts:["Events propagating from child to parent elements","Loading events first","CSS animation events","DOM events fired multiple times"], ans:0 },
  { id:10, q:"What does 'async' before a function do in JavaScript?", opts:["Makes the function return a Promise","Makes it run faster","Prevents side effects","Makes it synchronous"], ans:0 },
  { id:11, q:"What is 'lazy loading'?", opts:["Loading resources only when needed","A slow internet connection","CSS animation delay","A loading spinner component"], ans:0 },
  { id:12, q:"Which tool bundles JavaScript modules for the browser?", opts:["Webpack / Vite","npm","Babel","ESLint"], ans:0 },
  { id:13, q:"What is the difference between 'display: none' and 'visibility: hidden'?", opts:["display:none removes from layout; visibility:hidden keeps space","Both are identical","visibility:hidden removes from layout","display:none only hides visually"], ans:0 },
  { id:14, q:"What is ARIA in web development?", opts:["Accessible Rich Internet Applications — improves accessibility","A CSS preprocessor","A JavaScript testing framework","An image format"], ans:0 },
  { id:15, q:"What does localStorage store?", opts:["Key-value pairs that persist across browser sessions","Session data that clears on tab close","Server-side data","Encrypted tokens only"], ans:0 },
  { id:16, q:"What is the purpose of CSS media queries?", opts:["Apply styles based on screen size/device","Fetch external CSS files","Animate elements","Filter DOM elements"], ans:0 },
  { id:17, q:"What is TypeScript?", opts:["A statically-typed superset of JavaScript","A CSS framework","A backend language","A database query language"], ans:0 },
  { id:18, q:"Which React concept prevents unnecessary re-renders?", opts:["React.memo / useMemo","useEffect","useState","useRef"], ans:0 },
  { id:19, q:"What is the purpose of a Service Worker?", opts:["Enable offline capabilities and push notifications","Serve static files","Manage database connections","Handle server-side rendering"], ans:0 },
  { id:20, q:"Which CSS property creates a smooth transition between values?", opts:["transition","animation","transform","keyframes"], ans:0 },
];

const backendDeveloper: Question[] = [
  { id:1,  q:"What is the purpose of an API (Application Programming Interface)?", opts:["Enables communication between software components","Renders HTML pages","Stores database records","Manages CSS styles"], ans:0 },
  { id:2,  q:"Which HTTP status code means 'Created'?", opts:["201","200","204","301"], ans:0 },
  { id:3,  q:"What is database indexing used for?", opts:["Speed up query performance","Backup data","Encrypt data","Replicate data"], ans:0 },
  { id:4,  q:"What is the difference between SQL and NoSQL?", opts:["SQL uses structured tables; NoSQL uses flexible schemas","SQL is faster always","NoSQL cannot store strings","SQL is only for analytics"], ans:0 },
  { id:5,  q:"What is OAuth 2.0?", opts:["An authorisation framework for granting third-party access","A database protocol","An encryption standard","A caching mechanism"], ans:0 },
  { id:6,  q:"What does 'stateless' mean in REST?", opts:["Each request contains all info needed — no server session","The server stores session state","The client has no state","Responses are not cached"], ans:0 },
  { id:7,  q:"What is caching used for in backend systems?", opts:["Store frequently accessed data to reduce latency","Secure API endpoints","Validate request bodies","Monitor server health"], ans:0 },
  { id:8,  q:"What is a message queue (e.g. RabbitMQ, Kafka)?", opts:["Async communication between services via buffered messages","A REST API standard","A database type","A load balancer"], ans:0 },
  { id:9,  q:"What is Docker used for?", opts:["Containerising applications for consistent deployment","Database management","Frontend bundling","Load testing"], ans:0 },
  { id:10, q:"What is a race condition?", opts:["Unexpected behaviour when two processes access shared data concurrently","A competitive algorithm","A database deadlock","A slow API response"], ans:0 },
  { id:11, q:"What is the N+1 query problem?", opts:["Fetching N extra queries per record instead of using joins","Server returning N+1 extra fields","A loop running once too many times","An off-by-one error in SQL"], ans:0 },
  { id:12, q:"What does ACID stand for in databases?", opts:["Atomicity, Consistency, Isolation, Durability","Access, Control, Integrity, Data","Async, Concurrent, Indexed, Distributed","Availability, Consistency, Integrity, Durability"], ans:0 },
  { id:13, q:"What is rate limiting?", opts:["Restricting the number of API requests per time window","Limiting database size","Capping server memory","Throttling CSS animations"], ans:0 },
  { id:14, q:"What is a microservice architecture?", opts:["Small independent services each handling a single capability","A monolithic application split into files","A CSS design pattern","A type of API gateway"], ans:0 },
  { id:15, q:"Which Node.js module handles HTTP servers natively?", opts:["http","express","fs","path"], ans:0 },
  { id:16, q:"What is connection pooling?", opts:["Reusing database connections to avoid overhead of repeated connections","Grouping API endpoints","Batching SQL queries","Caching query results"], ans:0 },
  { id:17, q:"What is the purpose of a reverse proxy (e.g., Nginx)?", opts:["Sit in front of servers to load balance and cache","Store server-side sessions","Compile backend code","Encrypt database fields"], ans:0 },
  { id:18, q:"What is bcrypt used for?", opts:["Hashing passwords securely","Encrypting API payloads","Generating JWT tokens","Compressing files"], ans:0 },
  { id:19, q:"What is eventual consistency in distributed systems?", opts:["Replicas become consistent after some delay — not immediately","Data is immediately consistent everywhere","A type of SQL transaction","A cache invalidation strategy"], ans:0 },
  { id:20, q:"What does 'idempotent' mean for an HTTP method?", opts:["Calling it multiple times has the same effect as once","It always returns 200","It modifies data every call","It requires authentication"], ans:0 },
];

const aiProductDeveloper: Question[] = [
  { id:1,  q:"What is a 'product roadmap'?", opts:["A prioritised plan outlining product goals and features over time","A technical architecture diagram","A marketing plan","A user testing script"], ans:0 },
  { id:2,  q:"What does LLM stand for in AI?", opts:["Large Language Model","Linear Learning Machine","Layered Logic Module","Long-term Learning Memory"], ans:0 },
  { id:3,  q:"What is 'prompt engineering'?", opts:["Crafting inputs to guide LLMs towards desired outputs","Building AI hardware","Writing Python scripts","Designing database schemas"], ans:0 },
  { id:4,  q:"What is 'RAG' (Retrieval-Augmented Generation)?", opts:["Combining a retrieval system with LLM generation for grounded answers","A data cleaning method","A type of neural network","A reinforcement algorithm"], ans:0 },
  { id:5,  q:"What metric measures how closely a feature aligns with user needs?", opts:["User story acceptance criteria / user satisfaction score","Lines of code","API response time","Uptime percentage"], ans:0 },
  { id:6,  q:"What is 'model hallucination' in LLMs?", opts:["The model generates confident but factually incorrect outputs","A GPU error during training","A data preprocessing bug","An overfitting issue"], ans:0 },
  { id:7,  q:"What is 'fine-tuning' a model?", opts:["Further training a pre-trained model on domain-specific data","Building a model from scratch","Pruning unused layers","Deploying to production"], ans:0 },
  { id:8,  q:"What is an 'API wrapper' in an AI product?", opts:["A layer that simplifies calling an external AI API","A UI component","A database layer","A caching strategy"], ans:0 },
  { id:9,  q:"What does 'token' mean in LLM context?", opts:["A unit of text (roughly a word/subword) the model processes","An authentication credential","A billing unit only","A line of code"], ans:0 },
  { id:10, q:"What is 'context window' in an LLM?", opts:["The maximum text the model can process in one call","The browser viewport","The model's memory limit","The GPU memory"], ans:0 },
  { id:11, q:"What is 'A/B testing' in product development?", opts:["Comparing two variants to determine which performs better","Testing on Android and iOS","Running two servers simultaneously","Alpha and beta releases"], ans:0 },
  { id:12, q:"What is 'latency' in AI product performance?", opts:["Time from request to response","Number of requests per second","Model accuracy","Cost per API call"], ans:0 },
  { id:13, q:"What is the Minimum Viable Product (MVP) concept?", opts:["The smallest product version that delivers core value and can be tested","A fully featured first release","A prototype with no real functionality","A beta version for internal testing only"], ans:0 },
  { id:14, q:"What is 'semantic search'?", opts:["Search that understands meaning/intent rather than exact keywords","A faster keyword search","A boolean filter","A SQL LIKE query"], ans:0 },
  { id:15, q:"What is 'streaming' in LLM APIs?", opts:["Delivering tokens progressively as generated rather than waiting for full response","Sending audio files","Uploading training data","Caching model outputs"], ans:0 },
  { id:16, q:"What is 'vector database' used for in AI applications?", opts:["Storing and querying high-dimensional embeddings for semantic similarity","Traditional SQL queries","Image storage","Session management"], ans:0 },
  { id:17, q:"What does 'grounding' an AI response mean?", opts:["Anchoring outputs to verified facts/sources to reduce hallucinations","Running the model on GPU","Training on labelled data","Compressing model weights"], ans:0 },
  { id:18, q:"What is 'observability' in a deployed AI product?", opts:["Monitoring inputs, outputs, latency, and errors in production","A UI testing strategy","A model training metric","A data labelling process"], ans:0 },
  { id:19, q:"What is 'responsible AI'?", opts:["Building AI that is fair, transparent, safe, and accountable","Only open-source AI","AI that self-corrects","AI with no bias at all"], ans:0 },
  { id:20, q:"What is 'chaining' in LLM applications (e.g. LangChain)?", opts:["Connecting multiple LLM calls/tools in a pipeline to solve complex tasks","Linking UI components","Joining database tables","Connecting APIs"], ans:0 },
];

const softwareDeveloper: Question[] = [
  { id:1,  q:"What is Big O notation used for?", opts:["Describing algorithm time/space complexity","A programming language","A design pattern","A testing framework"], ans:0 },
  { id:2,  q:"What is a stack data structure?", opts:["LIFO (Last In First Out) structure","FIFO structure","Sorted array","A linked list with random access"], ans:0 },
  { id:3,  q:"What is recursion?", opts:["A function calling itself with a base case to stop","A loop with a counter","A method with multiple parameters","An async function"], ans:0 },
  { id:4,  q:"What is the Singleton design pattern?", opts:["Ensures a class has only one instance globally","Creates multiple instances","Provides a factory of objects","Wraps a legacy interface"], ans:0 },
  { id:5,  q:"What is time complexity of binary search?", opts:["O(log n)","O(n)","O(n²)","O(1)"], ans:0 },
  { id:6,  q:"What does DRY stand for in software?", opts:["Don't Repeat Yourself","Do Refactor Yearly","Dynamic Runtime YAML","Design Reusable Yet-another-pattern"], ans:0 },
  { id:7,  q:"What is a linked list?", opts:["A sequence of nodes where each points to the next","A sorted array","A hash table","A tree structure"], ans:0 },
  { id:8,  q:"What is SOLID in OOP?", opts:["5 principles: Single Responsibility, Open/Closed, Liskov, Interface Segregation, Dependency Inversion","A design pattern","A testing methodology","A database principle"], ans:0 },
  { id:9,  q:"What is garbage collection in programming languages?", opts:["Automatic memory management — reclaims unused memory","Removing unused code","Cleaning log files","Purging database records"], ans:0 },
  { id:10, q:"What is the Observer pattern?", opts:["An object (subject) notifies dependents (observers) on state change","A singleton pattern variant","A way to cache data","A type of inheritance"], ans:0 },
  { id:11, q:"What is the time complexity of bubble sort?", opts:["O(n²)","O(n log n)","O(log n)","O(n)"], ans:0 },
  { id:12, q:"What is a hash table?", opts:["Data structure mapping keys to values via a hash function","A sorted list","A tree with key-value nodes","An indexed array"], ans:0 },
  { id:13, q:"What is version control used for?", opts:["Tracking code changes and enabling collaboration","Compiling code","Testing code","Deploying applications"], ans:0 },
  { id:14, q:"What is 'technical debt'?", opts:["Cost of shortcuts taken now that must be fixed later","Money owed for software licences","Server infrastructure costs","Bug count in production"], ans:0 },
  { id:15, q:"What is a binary tree?", opts:["A tree where each node has at most 2 children","A tree sorted alphabetically","A tree with 2 levels","A doubly-linked list"], ans:0 },
  { id:16, q:"What does CI/CD stand for?", opts:["Continuous Integration / Continuous Deployment","Code Inspection / Code Deployment","Component Integration / Component Delivery","Continuous Iteration / Continuous Design"], ans:0 },
  { id:17, q:"What is a deadlock in concurrent programming?", opts:["Two or more processes waiting on each other indefinitely","A slow database query","A memory overflow","An infinite loop"], ans:0 },
  { id:18, q:"What is polymorphism in OOP?", opts:["The ability of objects of different types to be treated as the same type","Inheriting from multiple classes","Encapsulating private data","Overloading operators"], ans:0 },
  { id:19, q:"What is the Factory Method pattern?", opts:["Defines an interface for creating objects, letting subclasses decide the type","A singleton factory","A way to destroy objects","A caching pattern"], ans:0 },
  { id:20, q:"What is 'memoisation'?", opts:["Caching function results for known inputs to avoid recomputation","A type of recursion","A debugging technique","A code review process"], ans:0 },
];

const testingQA: Question[] = [
  { id:1,  q:"What is 'unit testing'?", opts:["Testing individual functions/components in isolation","Testing the entire system","Testing the UI only","Testing API endpoints"], ans:0 },
  { id:2,  q:"What is the purpose of regression testing?", opts:["Ensure new changes don't break existing functionality","Test new features only","Test performance","Test security"], ans:0 },
  { id:3,  q:"What does Selenium automate?", opts:["Browser interactions for web testing","Mobile app testing","API testing","Database queries"], ans:0 },
  { id:4,  q:"What is a 'test case'?", opts:["A set of conditions, inputs, and expected outputs for a specific test","A bug report","A test plan document","A deployment script"], ans:0 },
  { id:5,  q:"What is boundary value analysis?", opts:["Testing at the edges of valid input ranges","Testing only invalid inputs","Testing performance limits","Testing UI boundaries"], ans:0 },
  { id:6,  q:"What is a 'smoke test'?", opts:["A quick sanity check verifying core features work before deeper testing","A performance test","A destructive test","A security test"], ans:0 },
  { id:7,  q:"What does API testing verify?", opts:["Request/response contracts, status codes, and data integrity","UI rendering","Database schema","Network latency only"], ans:0 },
  { id:8,  q:"What is 'test coverage'?", opts:["Percentage of code executed by tests","Number of test cases written","Pass/fail ratio","Time spent testing"], ans:0 },
  { id:9,  q:"What does JIRA primarily track?", opts:["Issues, bugs, and project tasks","Code commits","CI/CD pipelines","Server performance"], ans:0 },
  { id:10, q:"What is the difference between verification and validation?", opts:["Verification: are we building it right? Validation: are we building the right thing?","They are the same","Verification is for UI; Validation for APIs","Validation happens before development"], ans:0 },
  { id:11, q:"What is 'exploratory testing'?", opts:["Simultaneous learning, test design, and execution without predefined scripts","Testing all code paths","Automated testing","Load testing"], ans:0 },
  { id:12, q:"What is a 'mock' in unit testing?", opts:["A fake object simulating the behaviour of real dependencies","A live API call","A performance snapshot","A visual snapshot"], ans:0 },
  { id:13, q:"What is load testing?", opts:["Testing system behaviour under expected load conditions","Testing with invalid data","Testing individual functions","Testing UI responsiveness"], ans:0 },
  { id:14, q:"Which HTTP status code should a successful GET return?", opts:["200","201","404","500"], ans:0 },
  { id:15, q:"What is 'shift-left testing'?", opts:["Introducing testing earlier in the development lifecycle","Testing on left-hand devices","Moving QA to a different team","Testing the left side of the UI"], ans:0 },
  { id:16, q:"What is a bug's 'severity' vs 'priority'?", opts:["Severity: impact on system; Priority: urgency of fixing","They are the same","Priority: impact; Severity: urgency","Severity is for UI bugs only"], ans:0 },
  { id:17, q:"What does TDD stand for?", opts:["Test-Driven Development","Testing Documentation Design","Technology Development Deploy","Test Data Discovery"], ans:0 },
  { id:18, q:"What is 'negative testing'?", opts:["Testing with invalid, unexpected, or out-of-range inputs","Testing without any assertions","Testing error messages only","Running tests in reverse order"], ans:0 },
  { id:19, q:"What is a 'flaky test'?", opts:["A test that passes/fails inconsistently without code changes","A badly written test","A test with no assertions","A slow performance test"], ans:0 },
  { id:20, q:"What is Postman used for?", opts:["Testing and exploring REST APIs","Automating browser tests","Load testing","Database querying"], ans:0 },
];

const cyberSecurity: Question[] = [
  { id:1,  q:"What is SQL injection?", opts:["Inserting malicious SQL into user inputs to manipulate a database","A database optimisation","A type of encryption","A network attack"], ans:0 },
  { id:2,  q:"What does XSS stand for?", opts:["Cross-Site Scripting","External Server Script","Cross-System Security","XML Security Schema"], ans:0 },
  { id:3,  q:"What is a 'man-in-the-middle' (MITM) attack?", opts:["Attacker secretly intercepts and relays communication between two parties","A brute-force attack","A social engineering attack","A DDoS attack"], ans:0 },
  { id:4,  q:"What is two-factor authentication (2FA)?", opts:["Requires two forms of verification — something you know + something you have/are","Two separate passwords","Two security questions","Two-step registration"], ans:0 },
  { id:5,  q:"What does CIA triad stand for in security?", opts:["Confidentiality, Integrity, Availability","Classification, Identification, Authentication","Control, Isolation, Access","Cyber, Infrastructure, Audit"], ans:0 },
  { id:6,  q:"What is a firewall?", opts:["A system that monitors and controls network traffic based on security rules","An antivirus tool","A VPN service","An intrusion detection system"], ans:0 },
  { id:7,  q:"What is 'phishing'?", opts:["Fraudulent emails/messages tricking users into revealing sensitive info","A network scanning technique","A type of malware","A brute-force attack"], ans:0 },
  { id:8,  q:"What is the purpose of HTTPS?", opts:["Encrypt communication between browser and server using TLS","Speed up page loading","Enable cookies","Enable CORS"], ans:0 },
  { id:9,  q:"What is a 'zero-day vulnerability'?", opts:["A flaw unknown to the software vendor with no existing patch","A bug fixed in zero days","A newly created vulnerability","An old known vulnerability"], ans:0 },
  { id:10, q:"What does 'least privilege principle' mean?", opts:["Users/systems get only the minimum access needed for their role","Giving all users admin rights initially","Removing all permissions after a breach","Sharing privileges equally"], ans:0 },
  { id:11, q:"What is AES (Advanced Encryption Standard)?", opts:["A symmetric encryption algorithm widely used for securing data","An asymmetric key exchange","A hashing algorithm","A digital signature method"], ans:0 },
  { id:12, q:"What is a DDoS attack?", opts:["Overwhelming a server with traffic from multiple sources to cause downtime","A data breach","A phishing attack","A SQL injection"], ans:0 },
  { id:13, q:"What does 'penetration testing' involve?", opts:["Authorised simulated attacks to find vulnerabilities before malicious actors do","Inserting hardware backdoors","Scanning public IP addresses","Installing monitoring software"], ans:0 },
  { id:14, q:"What is a VPN?", opts:["Creates an encrypted tunnel for secure communication over public networks","A type of antivirus","A network monitoring tool","A password manager"], ans:0 },
  { id:15, q:"What is ransomware?", opts:["Malware that encrypts victim's data and demands payment for the key","A type of phishing","A network scanner","A keylogger"], ans:0 },
  { id:16, q:"What does OWASP stand for?", opts:["Open Web Application Security Project","Open Worldwide API Security Protocol","Online Web Audit Security Program","Open-source Web Application Scanning Platform"], ans:0 },
  { id:17, q:"What is 'hashing' in security?", opts:["A one-way function converting data to a fixed-length digest","Reversible encryption","Compressing data","Signing a document"], ans:0 },
  { id:18, q:"What is 'social engineering' in cybersecurity?", opts:["Manipulating people into revealing confidential information","Writing malicious code","Exploiting software bugs","Brute-forcing passwords"], ans:0 },
  { id:19, q:"What is a digital certificate used for?", opts:["Verifying the identity of a website/entity and enabling encrypted communication","Storing passwords","Encrypting local files","Scanning for viruses"], ans:0 },
  { id:20, q:"What is 'port scanning'?", opts:["Probing a server's open ports to discover services and vulnerabilities","A type of encryption","A firewall bypass","A password reset method"], ans:0 },
];

export const ASSESSMENT_TRACKS: AssessmentTrack[] = [
  { slug: "aptitude",             label: "Aptitude",                    duration: 30, questions: aptitude           },
  { slug: "digital-marketing",    label: "Digital Marketing",           duration: 30, questions: digitalMarketing   },
  { slug: "data-science",         label: "Data Science",                duration: 35, questions: dataScience        },
  { slug: "data-analyst",         label: "Data Analyst",                duration: 30, questions: dataAnalyst        },
  { slug: "full-stack-developer", label: "Full Stack Developer",        duration: 35, questions: fullStack          },
  { slug: "python-developer",     label: "Python Developer",            duration: 30, questions: pythonDeveloper    },
  { slug: "medical-coding",       label: "Medical Coding",              duration: 35, questions: medicalCoding      },
  { slug: "ai-ds",                label: "AI and DS",                   duration: 35, questions: aiDs              },
  { slug: "frontend-developer",   label: "Front-End Developer",         duration: 30, questions: frontendDeveloper  },
  { slug: "backend-developer",    label: "Back-End Developer",          duration: 35, questions: backendDeveloper   },
  { slug: "ai-product-developer", label: "AI Product Developer",        duration: 30, questions: aiProductDeveloper },
  { slug: "software-developer",   label: "Software Developer",          duration: 35, questions: softwareDeveloper  },
  { slug: "testing-qa",           label: "Testing (QA)",                duration: 30, questions: testingQA          },
  { slug: "cyber-security",       label: "Cyber Security",              duration: 35, questions: cyberSecurity      },
];

export function getTrack(slug: string): AssessmentTrack | undefined {
  return ASSESSMENT_TRACKS.find(t => t.slug === slug);
}
