import type { Challenge } from "@upgradian/types";

export const SEED_CHALLENGES: Challenge[] = [
  {
    id: "seed-001",
    title: "Two Sum",
    slug: "two-sum",
    description: "Given an array of integers `nums` and an integer `target`, return indices of the two numbers such that they add up to `target`.\n\nYou may assume that each input has exactly one solution, and you may not use the same element twice.\n\nExample:\nInput: nums = [2,7,11,15], target = 9\nOutput: [0,1]\nExplanation: nums[0] + nums[1] = 9",
    difficulty: "easy",
    language: "python",
    xp_reward: 50,
    time_limit_ms: 2000,
    memory_limit_mb: 256,
    starter_code: "def two_sum(nums, target):\n    # Write your solution here\n    pass\n\n# Test\nprint(two_sum([2,7,11,15], 9))  # [0, 1]",
    test_cases: [
      { input: "2 7 11 15\n9", expected_output: "0 1", is_hidden: false },
      { input: "3 2 4\n6", expected_output: "1 2", is_hidden: true },
    ],
    tags: ["Arrays", "Hash Map"],
    is_active: true,
    created_at: "2025-01-01T00:00:00Z",
    solved_by: 12840,
    acceptance_rate: 72,
  },
  {
    id: "seed-002",
    title: "Reverse String",
    slug: "reverse-string",
    description: "Write a function that reverses a string. The input string is given as an array of characters `s`.\n\nYou must do this by modifying the input array in-place with O(1) extra memory.\n\nExample:\nInput: s = ['h','e','l','l','o']\nOutput: ['o','l','l','e','h']",
    difficulty: "easy",
    language: "javascript",
    xp_reward: 50,
    time_limit_ms: 1000,
    memory_limit_mb: 128,
    starter_code: "/**\n * @param {character[]} s\n * @return {void}\n */\nfunction reverseString(s) {\n    // Write your solution here\n}\n\n// Test\nconst arr = ['h','e','l','l','o'];\nreverseString(arr);\nconsole.log(arr); // ['o','l','l','e','h']",
    test_cases: [
      { input: "hello", expected_output: "olleh", is_hidden: false },
      { input: "Hannah", expected_output: "hannaH", is_hidden: true },
    ],
    tags: ["Strings", "Two Pointers"],
    is_active: true,
    created_at: "2025-01-01T00:00:00Z",
    solved_by: 18920,
    acceptance_rate: 82,
  },
  {
    id: "seed-003",
    title: "Fibonacci Number",
    slug: "fibonacci-number",
    description: "The Fibonacci numbers, commonly denoted F(n) form a sequence where F(0) = 0, F(1) = 1, and F(n) = F(n-1) + F(n-2) for n > 1.\n\nGiven n, calculate F(n).\n\nExample:\nInput: n = 4\nOutput: 3\nExplanation: F(4) = F(3) + F(2) = 2 + 1 = 3",
    difficulty: "easy",
    language: "python",
    xp_reward: 50,
    time_limit_ms: 1000,
    memory_limit_mb: 128,
    starter_code: "def fib(n: int) -> int:\n    # Write your solution here\n    pass\n\n# Test\nprint(fib(4))  # 3\nprint(fib(10)) # 55",
    test_cases: [
      { input: "4", expected_output: "3", is_hidden: false },
      { input: "10", expected_output: "55", is_hidden: true },
    ],
    tags: ["Recursion", "Dynamic Programming"],
    is_active: true,
    created_at: "2025-01-01T00:00:00Z",
    solved_by: 15600,
    acceptance_rate: 79,
  },
  {
    id: "seed-004",
    title: "Valid Palindrome",
    slug: "valid-palindrome",
    description: "A phrase is a palindrome if, after converting all uppercase letters to lowercase and removing all non-alphanumeric characters, it reads the same forward and backward.\n\nGiven a string s, return true if it is a palindrome, or false otherwise.\n\nExample:\nInput: s = 'A man, a plan, a canal: Panama'\nOutput: true",
    difficulty: "easy",
    language: "javascript",
    xp_reward: 50,
    time_limit_ms: 1000,
    memory_limit_mb: 128,
    starter_code: "/**\n * @param {string} s\n * @return {boolean}\n */\nfunction isPalindrome(s) {\n    // Write your solution here\n}\n\n// Test\nconsole.log(isPalindrome('A man, a plan, a canal: Panama')); // true\nconsole.log(isPalindrome('race a car')); // false",
    test_cases: [
      { input: "A man, a plan, a canal: Panama", expected_output: "true", is_hidden: false },
      { input: "race a car", expected_output: "false", is_hidden: true },
    ],
    tags: ["Strings", "Two Pointers"],
    is_active: true,
    created_at: "2025-01-01T00:00:00Z",
    solved_by: 11200,
    acceptance_rate: 69,
  },
  {
    id: "seed-005",
    title: "Maximum Subarray",
    slug: "maximum-subarray",
    description: "Given an integer array nums, find the subarray with the largest sum, and return its sum (Kadane's Algorithm).\n\nExample:\nInput: nums = [-2,1,-3,4,-1,2,1,-5,4]\nOutput: 6\nExplanation: The subarray [4,-1,2,1] has the largest sum 6.",
    difficulty: "medium",
    language: "python",
    xp_reward: 100,
    time_limit_ms: 2000,
    memory_limit_mb: 256,
    starter_code: "def max_subarray(nums: list[int]) -> int:\n    # Write your solution here\n    pass\n\n# Test\nprint(max_subarray([-2,1,-3,4,-1,2,1,-5,4]))  # 6",
    test_cases: [
      { input: "-2 1 -3 4 -1 2 1 -5 4", expected_output: "6", is_hidden: false },
      { input: "1", expected_output: "1", is_hidden: true },
    ],
    tags: ["Arrays", "Dynamic Programming"],
    is_active: true,
    created_at: "2025-01-01T00:00:00Z",
    solved_by: 9840,
    acceptance_rate: 58,
  },
  {
    id: "seed-006",
    title: "Valid Parentheses",
    slug: "valid-parentheses",
    description: "Given a string s containing just the characters '(', ')', '{', '}', '[' and ']', determine if the input string is valid.\n\nAn input string is valid if:\n1. Open brackets must be closed by the same type of brackets.\n2. Open brackets must be closed in the correct order.\n\nExample:\nInput: s = '()[]{}'\nOutput: true",
    difficulty: "easy",
    language: "javascript",
    xp_reward: 50,
    time_limit_ms: 1000,
    memory_limit_mb: 128,
    starter_code: "/**\n * @param {string} s\n * @return {boolean}\n */\nfunction isValid(s) {\n    // Write your solution here\n}\n\n// Test\nconsole.log(isValid('()[]{}'));  // true\nconsole.log(isValid('(]'));     // false",
    test_cases: [
      { input: "()[]{}", expected_output: "true", is_hidden: false },
      { input: "(]", expected_output: "false", is_hidden: true },
    ],
    tags: ["Stacks", "Strings"],
    is_active: true,
    created_at: "2025-01-01T00:00:00Z",
    solved_by: 14300,
    acceptance_rate: 74,
  },
  {
    id: "seed-007",
    title: "Binary Search",
    slug: "binary-search",
    description: "Given an array of integers nums which is sorted in ascending order, and an integer target, write a function to search target in nums. If target exists, return its index. Otherwise, return -1.\n\nYou must write an algorithm with O(log n) runtime complexity.\n\nExample:\nInput: nums = [-1,0,3,5,9,12], target = 9\nOutput: 4",
    difficulty: "easy",
    language: "python",
    xp_reward: 75,
    time_limit_ms: 1000,
    memory_limit_mb: 128,
    starter_code: "def binary_search(nums: list[int], target: int) -> int:\n    # Write your solution here\n    pass\n\n# Test\nprint(binary_search([-1,0,3,5,9,12], 9))  # 4\nprint(binary_search([-1,0,3,5,9,12], 2))  # -1",
    test_cases: [
      { input: "-1 0 3 5 9 12\n9", expected_output: "4", is_hidden: false },
      { input: "-1 0 3 5 9 12\n2", expected_output: "-1", is_hidden: true },
    ],
    tags: ["Sorting", "Binary Search"],
    is_active: true,
    created_at: "2025-01-01T00:00:00Z",
    solved_by: 13500,
    acceptance_rate: 77,
  },
  {
    id: "seed-008",
    title: "Merge Sorted Array",
    slug: "merge-sorted-array",
    description: "You are given two integer arrays nums1 and nums2, sorted in non-decreasing order, and two integers m and n, representing the number of elements in nums1 and nums2 respectively.\n\nMerge nums1 and nums2 into a single array sorted in non-decreasing order.\n\nExample:\nInput: nums1 = [1,2,3,0,0,0], m = 3, nums2 = [2,5,6], n = 3\nOutput: [1,2,2,3,5,6]",
    difficulty: "easy",
    language: "python",
    xp_reward: 75,
    time_limit_ms: 1000,
    memory_limit_mb: 128,
    starter_code: "def merge(nums1: list[int], m: int, nums2: list[int], n: int) -> None:\n    # Modify nums1 in-place\n    pass\n\n# Test\nnums1 = [1,2,3,0,0,0]\nmerge(nums1, 3, [2,5,6], 3)\nprint(nums1)  # [1,2,2,3,5,6]",
    test_cases: [
      { input: "1 2 3 0 0 0\n3\n2 5 6\n3", expected_output: "1 2 2 3 5 6", is_hidden: false },
    ],
    tags: ["Arrays", "Sorting"],
    is_active: true,
    created_at: "2025-01-01T00:00:00Z",
    solved_by: 10900,
    acceptance_rate: 65,
  },
  {
    id: "seed-009",
    title: "Climbing Stairs",
    slug: "climbing-stairs",
    description: "You are climbing a staircase. It takes n steps to reach the top.\nEach time you can either climb 1 or 2 steps. In how many distinct ways can you climb to the top?\n\nExample:\nInput: n = 3\nOutput: 3\nExplanation: 1+1+1, 1+2, 2+1",
    difficulty: "easy",
    language: "javascript",
    xp_reward: 75,
    time_limit_ms: 1000,
    memory_limit_mb: 128,
    starter_code: "/**\n * @param {number} n\n * @return {number}\n */\nfunction climbStairs(n) {\n    // Write your solution here\n}\n\nconsole.log(climbStairs(3)); // 3\nconsole.log(climbStairs(5)); // 8",
    test_cases: [
      { input: "3", expected_output: "3", is_hidden: false },
      { input: "5", expected_output: "8", is_hidden: true },
    ],
    tags: ["Dynamic Programming", "Recursion"],
    is_active: true,
    created_at: "2025-01-01T00:00:00Z",
    solved_by: 16700,
    acceptance_rate: 80,
  },
  {
    id: "seed-010",
    title: "Longest Common Prefix",
    slug: "longest-common-prefix",
    description: "Write a function to find the longest common prefix string amongst an array of strings.\nIf there is no common prefix, return an empty string \"\".\n\nExample:\nInput: strs = ['flower','flow','flight']\nOutput: 'fl'",
    difficulty: "easy",
    language: "python",
    xp_reward: 50,
    time_limit_ms: 1000,
    memory_limit_mb: 128,
    starter_code: "def longest_common_prefix(strs: list[str]) -> str:\n    # Write your solution here\n    pass\n\nprint(longest_common_prefix(['flower','flow','flight']))  # 'fl'\nprint(longest_common_prefix(['dog','racecar','car']))     # ''",
    test_cases: [
      { input: "flower flow flight", expected_output: "fl", is_hidden: false },
      { input: "dog racecar car", expected_output: "", is_hidden: true },
    ],
    tags: ["Strings"],
    is_active: true,
    created_at: "2025-01-01T00:00:00Z",
    solved_by: 12100,
    acceptance_rate: 70,
  },
  {
    id: "seed-011",
    title: "Group Anagrams",
    slug: "group-anagrams",
    description: "Given an array of strings strs, group the anagrams together. You can return the answer in any order.\n\nExample:\nInput: strs = ['eat','tea','tan','ate','nat','bat']\nOutput: [['bat'],['nat','tan'],['ate','eat','tea']]",
    difficulty: "medium",
    language: "python",
    xp_reward: 100,
    time_limit_ms: 2000,
    memory_limit_mb: 256,
    starter_code: "def group_anagrams(strs: list[str]) -> list[list[str]]:\n    # Write your solution here\n    pass\n\nprint(group_anagrams(['eat','tea','tan','ate','nat','bat']))",
    test_cases: [
      { input: "eat tea tan ate nat bat", expected_output: "[['eat','tea','ate'],['tan','nat'],['bat']]", is_hidden: false },
    ],
    tags: ["Arrays", "Strings", "Hash Map"],
    is_active: true,
    created_at: "2025-01-01T00:00:00Z",
    solved_by: 8900,
    acceptance_rate: 52,
  },
  {
    id: "seed-012",
    title: "Jump Game",
    slug: "jump-game",
    description: "You are given an integer array nums. You are initially positioned at the first index, and each element in the array represents your maximum jump length at that position.\n\nReturn true if you can reach the last index, or false otherwise.\n\nExample:\nInput: nums = [2,3,1,1,4]\nOutput: true",
    difficulty: "medium",
    language: "javascript",
    xp_reward: 100,
    time_limit_ms: 2000,
    memory_limit_mb: 256,
    starter_code: "/**\n * @param {number[]} nums\n * @return {boolean}\n */\nfunction canJump(nums) {\n    // Write your solution here\n}\n\nconsole.log(canJump([2,3,1,1,4])); // true\nconsole.log(canJump([3,2,1,0,4])); // false",
    test_cases: [
      { input: "2 3 1 1 4", expected_output: "true", is_hidden: false },
      { input: "3 2 1 0 4", expected_output: "false", is_hidden: true },
    ],
    tags: ["Dynamic Programming", "Arrays"],
    is_active: true,
    created_at: "2025-01-01T00:00:00Z",
    solved_by: 7600,
    acceptance_rate: 48,
  },
  {
    id: "seed-013",
    title: "Coin Change",
    slug: "coin-change",
    description: "You are given an integer array coins representing coins of different denominations and an integer amount representing a total amount of money.\n\nReturn the fewest number of coins needed to make up that amount. If it cannot be achieved, return -1.\n\nExample:\nInput: coins = [1,5,11], amount = 15\nOutput: 3 (11 + 3×1 = 15? No — 5+5+5 = 15, answer is 3)",
    difficulty: "medium",
    language: "python",
    xp_reward: 125,
    time_limit_ms: 3000,
    memory_limit_mb: 256,
    starter_code: "def coin_change(coins: list[int], amount: int) -> int:\n    # Write your solution here (DP approach recommended)\n    pass\n\nprint(coin_change([1,5,11], 15))  # 3\nprint(coin_change([2], 3))         # -1",
    test_cases: [
      { input: "1 5 11\n15", expected_output: "3", is_hidden: false },
      { input: "2\n3", expected_output: "-1", is_hidden: true },
    ],
    tags: ["Dynamic Programming"],
    is_active: true,
    created_at: "2025-01-01T00:00:00Z",
    solved_by: 7200,
    acceptance_rate: 45,
  },
  {
    id: "seed-014",
    title: "Longest Palindromic Substring",
    slug: "longest-palindromic-substring",
    description: "Given a string s, return the longest palindromic substring in s.\n\nExample:\nInput: s = 'babad'\nOutput: 'bab' (or 'aba', both are valid)",
    difficulty: "medium",
    language: "python",
    xp_reward: 125,
    time_limit_ms: 3000,
    memory_limit_mb: 256,
    starter_code: "def longest_palindrome(s: str) -> str:\n    # Write your solution here\n    pass\n\nprint(longest_palindrome('babad'))  # 'bab' or 'aba'\nprint(longest_palindrome('cbbd'))   # 'bb'",
    test_cases: [
      { input: "babad", expected_output: "bab", is_hidden: false },
      { input: "cbbd", expected_output: "bb", is_hidden: true },
    ],
    tags: ["Strings", "Dynamic Programming"],
    is_active: true,
    created_at: "2025-01-01T00:00:00Z",
    solved_by: 6800,
    acceptance_rate: 42,
  },
  {
    id: "seed-015",
    title: "3Sum",
    slug: "three-sum",
    description: "Given an integer array nums, return all the triplets [nums[i], nums[j], nums[k]] such that i != j, i != k, j != k, and nums[i] + nums[j] + nums[k] == 0.\n\nThe solution set must not contain duplicate triplets.\n\nExample:\nInput: nums = [-1,0,1,2,-1,-4]\nOutput: [[-1,-1,2],[-1,0,1]]",
    difficulty: "medium",
    language: "python",
    xp_reward: 125,
    time_limit_ms: 3000,
    memory_limit_mb: 256,
    starter_code: "def three_sum(nums: list[int]) -> list[list[int]]:\n    # Write your solution here\n    pass\n\nprint(three_sum([-1,0,1,2,-1,-4]))  # [[-1,-1,2],[-1,0,1]]",
    test_cases: [
      { input: "-1 0 1 2 -1 -4", expected_output: "[[-1,-1,2],[-1,0,1]]", is_hidden: false },
    ],
    tags: ["Arrays", "Sorting"],
    is_active: true,
    created_at: "2025-01-01T00:00:00Z",
    solved_by: 5900,
    acceptance_rate: 38,
  },
  {
    id: "seed-016",
    title: "Trapping Rain Water",
    slug: "trapping-rain-water",
    description: "Given n non-negative integers representing an elevation map where the width of each bar is 1, compute how much water it can trap after raining.\n\nExample:\nInput: height = [0,1,0,2,1,0,1,3,2,1,2,1]\nOutput: 6",
    difficulty: "hard",
    language: "python",
    xp_reward: 200,
    time_limit_ms: 3000,
    memory_limit_mb: 256,
    starter_code: "def trap(height: list[int]) -> int:\n    # Write your solution here\n    pass\n\nprint(trap([0,1,0,2,1,0,1,3,2,1,2,1]))  # 6",
    test_cases: [
      { input: "0 1 0 2 1 0 1 3 2 1 2 1", expected_output: "6", is_hidden: false },
      { input: "4 2 0 3 2 5", expected_output: "9", is_hidden: true },
    ],
    tags: ["Arrays", "DSA"],
    is_active: true,
    created_at: "2025-01-01T00:00:00Z",
    solved_by: 4200,
    acceptance_rate: 33,
  },
  {
    id: "seed-017",
    title: "LRU Cache",
    slug: "lru-cache",
    description: "Design a data structure that follows the constraints of a Least Recently Used (LRU) cache.\n\nImplement the LRUCache class:\n- LRUCache(capacity): Initialize with positive size capacity\n- get(key): Return the value if key exists, else -1\n- put(key, value): Update or insert. If capacity exceeded, evict the least recently used key.\n\nBoth operations must run in O(1) time.",
    difficulty: "hard",
    language: "javascript",
    xp_reward: 200,
    time_limit_ms: 3000,
    memory_limit_mb: 256,
    starter_code: "class LRUCache {\n    constructor(capacity) {\n        this.capacity = capacity;\n        // Implement your data structure\n    }\n\n    get(key) {\n        // Return value or -1\n    }\n\n    put(key, value) {\n        // Insert/update\n    }\n}\n\n// Test\nconst cache = new LRUCache(2);\ncache.put(1, 1);\ncache.put(2, 2);\nconsole.log(cache.get(1));    // 1\ncache.put(3, 3);\nconsole.log(cache.get(2));    // -1 (evicted)",
    test_cases: [
      { input: "put 1 1\nput 2 2\nget 1\nput 3 3\nget 2", expected_output: "1\n-1", is_hidden: false },
    ],
    tags: ["DSA", "Design"],
    is_active: true,
    created_at: "2025-01-01T00:00:00Z",
    solved_by: 3100,
    acceptance_rate: 28,
  },
  {
    id: "seed-018",
    title: "Word Search",
    slug: "word-search",
    description: "Given an m x n grid of characters board and a string word, return true if word exists in the grid.\n\nThe word can be constructed from letters of sequentially adjacent cells, where adjacent cells are horizontally or vertically neighboring. The same letter cell may not be used more than once.\n\nExample:\nInput: board = [['A','B','C','E'],['S','F','C','S'],['A','D','E','E']], word = 'ABCCED'\nOutput: true",
    difficulty: "hard",
    language: "python",
    xp_reward: 175,
    time_limit_ms: 4000,
    memory_limit_mb: 256,
    starter_code: "def exist(board: list[list[str]], word: str) -> bool:\n    # Write your solution here (backtracking)\n    pass\n\nboard = [['A','B','C','E'],['S','F','C','S'],['A','D','E','E']]\nprint(exist(board, 'ABCCED'))  # True\nprint(exist(board, 'ABCB'))    # False",
    test_cases: [
      { input: "ABCE SFCS ADEE\nABCCED", expected_output: "True", is_hidden: false },
    ],
    tags: ["DSA", "Recursion"],
    is_active: true,
    created_at: "2025-01-01T00:00:00Z",
    solved_by: 3800,
    acceptance_rate: 31,
  },
  {
    id: "seed-019",
    title: "Edit Distance",
    slug: "edit-distance",
    description: "Given two strings word1 and word2, return the minimum number of operations required to convert word1 to word2.\n\nYou have the following operations: Insert, Delete, Replace a character.\n\nExample:\nInput: word1 = 'horse', word2 = 'ros'\nOutput: 3\nExplanation: horse→rorse (replace h→r), rorse→rose (delete r), rose→ros (delete e)",
    difficulty: "hard",
    language: "javascript",
    xp_reward: 200,
    time_limit_ms: 3000,
    memory_limit_mb: 256,
    starter_code: "/**\n * @param {string} word1\n * @param {string} word2\n * @return {number}\n */\nfunction minDistance(word1, word2) {\n    // Write your DP solution here\n}\n\nconsole.log(minDistance('horse', 'ros'));     // 3\nconsole.log(minDistance('intention', 'execution')); // 5",
    test_cases: [
      { input: "horse\nros", expected_output: "3", is_hidden: false },
      { input: "intention\nexecution", expected_output: "5", is_hidden: true },
    ],
    tags: ["Dynamic Programming", "Strings"],
    is_active: true,
    created_at: "2025-01-01T00:00:00Z",
    solved_by: 3500,
    acceptance_rate: 29,
  },
  {
    id: "seed-020",
    title: "Merge Intervals",
    slug: "merge-intervals",
    description: "Given an array of intervals where intervals[i] = [start_i, end_i], merge all overlapping intervals, and return an array of the non-overlapping intervals.\n\nExample:\nInput: intervals = [[1,3],[2,6],[8,10],[15,18]]\nOutput: [[1,6],[8,10],[15,18]]",
    difficulty: "medium",
    language: "python",
    xp_reward: 100,
    time_limit_ms: 2000,
    memory_limit_mb: 256,
    starter_code: "def merge(intervals: list[list[int]]) -> list[list[int]]:\n    # Write your solution here\n    pass\n\nprint(merge([[1,3],[2,6],[8,10],[15,18]]))  # [[1,6],[8,10],[15,18]]",
    test_cases: [
      { input: "1 3\n2 6\n8 10\n15 18", expected_output: "[[1,6],[8,10],[15,18]]", is_hidden: false },
    ],
    tags: ["Arrays", "Sorting"],
    is_active: true,
    created_at: "2025-01-01T00:00:00Z",
    solved_by: 8400,
    acceptance_rate: 50,
  },
];
